# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.4.0"

[source]
paths = ["src/"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 180
tab-width = 4
use-tabs = false
space-after-logical-not-unary-prefix-operator = false
null-type-hint = "question"
space-before-arrow-function-parameter-list-parenthesis = true
always-break-named-arguments-list = false
preserve-breaking-member-access-chain = true
preserve-breaking-argument-list = true
preserve-breaking-array-like = true
preserve-breaking-parameter-list = true
preserve-breaking-attribute-list = true
preserve-breaking-conditional-expression = true
empty-line-after-opening-tag = false

[linter]
integrations = []

[linter.rules]
interface-name = { psr = false }
trait-name = { psr = false }
class-name = { psr = false }
literal-named-argument = { enabled = false } # todo
no-error-control-operator = { enabled = false }
no-boolean-literal-comparison = { enabled = false }
too-many-methods = { enabled = false }
kan-defect = { enabled = false }
cyclomatic-complexity = { enabled = false }
return-type = { ignore-arrow-function = true, ignore-closure = true }
parameter-type = { ignore-arrow-function = true, ignore-closure = true }
too-many-enum-cases = { enabled = false }
no-redundant-file = { enabled = false }
assertion-style = { style = "this" }
strict-assertions = { enabled = false }
no-else-clause = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
no-shorthand-ternary = { enabled = false }
no-assign-in-condition = { enabled = false }
strict-types = { enabled = true }
tagged-todo = { enabled = false }
excessive-parameter-list = { enabled = false }
halstead = { enabled = false }
prefer-arrow-function = { enabled = false }
prefer-first-class-callable = { enabled = false }
strict-behavior = { allow-loose-behavior = true }
no-redundant-use = { enabled = true }

[analyzer]
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = false
check-throws = true
allow-possibly-undefined-array-keys = true
perform-heuristic-checks = false
